import React from 'react'
import Head from 'next/head'
const SiteTitle = () => {
  return (
    <div>
    <Head>
      <title>TENCOBA</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logoup.png" />
    </Head>
  </div>
  )
}

export default SiteTitle