import Head from "next/head";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Feature from "@/components/Feature";
import Testimonials from "@/components/Testimonials";
import CTA from "@/components/CTA";
import Footer from "@/components/Footer";

const Landing = () => {
  return (
    <>
      <div>
        <Head>
          <title>TENCOBA</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logoup.png" />
        </Head>
      </div>
      <div>
        {/* <Head>
        <title> TENCOBA </title>
        <meta name="description" content="Generated by NextJS"/>
        <link rel="icon" href="/pro.icon"></link>
      </Head> */}
        <Navbar />
        <Hero />
        <Feature />
        <Testimonials />
        <CTA />
        <Footer />
      </div>
    </>
  );
};

export default Landing;
