import Navbar from "@/components/Navbar";
import Hero from "@/components/homepage/Hero";
import Feature from "@/components/homepage/Feature";
import Testimonials from "@/components/homepage/Testimonials";
import CTA from "@/components/homepage/CTA";
import Footer from "@/components/Footer";

const Landing = () => {
  return (
    <div>
      {/* <Head>
        <title> TENCOBA </title>
        <meta name="description" content="Generated by NextJS"/>
        <link rel="icon" href="/pro.icon"></link>
      </Head> */}
      <Navbar />
      <Hero />
      <Feature />
      <Testimonials />
      <CTA />
      <Footer />
    </div>
  );
};

export default Landing;
